version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/coconut_leaf_detection

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ai_api:
    build:
      context: ./ml/ai_api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./ml/ai_api:/app

volumes:
  mongo_data: